export const SAVE_RQUESTING = 'SAVE_RQUESTING'
export const SAVE_RQUESTED = 'SAVE_RQUESTED'
export const SAVE_RQUESTERROR = 'SAVE_RQUESTERROR'

export const COLLECT_REQUESTING = 'COLLECT_REQUESTING'
export const COLLECT_REQUESTED = 'COLLECT_REQUESTED'
export const COLLECT_REQUESTERROR = 'COLLECT_REQUESTERROR'