export const UNPAID_REQUESTING = 'UNPAID_REQUESTING'
export const UNPAID_REQUESTED = 'UNPAID_REQUESTED'
export const UNPAID_REQUESTERROR = 'UNPAID_REQUESTERROR'

export const UNPAID_REQUESTING1 = 'UNPAID_REQUESTING1'
export const UNPAID_REQUESTED1 = 'UNPAID_REQUESTED1'
export const UNPAID_REQUESTERROR1 = 'UNPAID_REQUESTERROR1'