export const CARLIST_RQUESTING = 'CARLIST_RQUESTING'
export const CARLIST_RQUESTED = 'CARLIST_RQUESTED'
export const CARLIST_RQUESTERROR = 'CARLIST_RQUESTERROR'

export const CAR_RQUESTING = 'CAR_RQUESTING'
export const CAR_RQUESTED = 'CAR_RQUESTED'
export const CAR_RQUESTERROR = 'CAR_RQUESTERROR'