export const ORDER_RQUESTING = 'ORDER_RQUESTING'
export const ORDER_RQUESTED = 'ORDER_RQUESTED'
export const ORDER_RQUESTERROR = 'ORDER_RQUESTERROR'

export const ORDERLIST_RQUESTING = 'ORDERLIST_RQUESTING'
export const ORDERLIST_RQUESTED = 'ORDERLIST_RQUESTED'
export const ORDERLIST_RQUESTERROR = 'ORDERLIST_RQUESTERROR'