export const ADDCART_RQUESTING = 'ADDCART_RQUESTING'
export const ADDCART_RQUESTED = 'ADDCART_RQUESTED'
export const ADDCART_RQUESTERROR = 'ADDCART_RQUESTERROR'

export const GETCARTCOUNT_RQUESTING = 'GETCARTCOUNT_RQUESTING'
export const GETCARTCOUNT_RQUESTED = 'GETCARTCOUNT_RQUESTED'
export const GETCARTCOUNT_RQUESTERROR = 'GETCARTCOUNT_RQUESTERROR'

export const ADDCOLLECT_RQUESTING = 'ADDCOLLECT_RQUESTING'
export const ADDCOLLECT_RQUESTED = 'ADDCOLLECT_RQUESTED'
export const ADDCOLLECT_RQUESTERROR = 'ADDCOLLECT_RQUESTERROR'

export const GETCOLLECT_RQUESTING = 'GETCOLLECT_RQUESTING'
export const GETCOLLECT_RQUESTED = 'GETCOLLECT_RQUESTED'
export const GETCOLLECT_RQUESTERROR = 'GETCOLLECT_RQUESTERROR'

export const CANCELCOLLECT_RQUESTING = 'GETCOLLECT_RQUESTING'
export const CANCELCOLLECT_RQUESTED = 'GETCOLLECT_RQUESTED'
export const CANCELCOLLECT_RQUESTERROR = 'GETCOLLECT_RQUESTERROR'

export const GETIMGURL_RQUESTING = 'GETIMGURL_RQUESTING'
export const GETIMGURL_RQUESTED = 'GETIMGURL_RQUESTED'
export const GETIMGURL_RQUESTERROR = 'GETIMGURL_RQUESTERROR'

export const GETCOLOR_RQUESTING = 'GETCOLOR_RQUESTING'
export const GETCOLOR_RQUESTED = 'GETCOLOR_RQUESTED'
export const GETCOLOR_RQUESTERROR = 'GETCOLOR_RQUESTERROR'

export const GETSIZE_RQUESTING = 'GETSIZE_RQUESTING'
export const GETSIZE_RQUESTED = 'GETSIZE_RQUESTED'
export const GETSIZE_RQUESTERROR = 'GETSIZE_RQUESTERROR'

export const COMMENT_RQUESTING = 'COMMENT_RQUESTING'
export const COMMENT_RQUESTED = 'COMMENT_RQUESTED'
export const COMMENT_RQUESTERROR = 'COMMENT_RQUESTERROR'

export const DETAILS_RQUESTING = 'DETAILS_RQUESTING'
export const DETAILS_RQUESTED = 'DETAILS_RQUESTED'
export const DETAILS_RQUESTERROR = 'DETAILS_RQUESTERROR'
