export const TABS_RQUESTING = 'TABS_RQUESTING'
export const TABS_RQUESTED = 'TABS_RQUESTED'
export const TABS_RQUESTERROR = 'TABS_RQUESTERROR'

export const BANNER_RQUESTING = 'BANNER_RQUESTING'
export const BANNER_RQUESTED = 'BANNER_RQUESTED'
export const BANNER_RQUESTERROR = 'BANNER_RQUESTERROR'
